# Generated by Django 5.1.6 on 2025-05-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
